name: zzz_book_store
description: "App mobile for 3Z Book Store"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  http: ^1.1.0
  intl: 0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.1
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  flutter_svg: ^2.0.10+1

  # UI
  awesome_bottom_bar: ^1.2.4
  carousel_slider: ^4.2.1
  rating_summary: ^1.0.2+1
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  flutter_slidable: ^3.1.0
  
  # Animations
  zoom_tap_animation: ^1.1.0

  # Utils
  cached_network_image: ^3.2.0
  readmore: ^3.0.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/onboarding/
    - assets/images/register/
    - assets/images/banner/
    - assets/images/product/
    - assets/images/author/
    - assets/images/product-detail/

  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca-Bold.ttf
          weight: 800